### PR TITLE
Upgrade to @sentry/node@7.1.1

### PR DESCRIPTION
**Pull request by segevfiner**
Upgrade to @sentry/node@7.1.1

### CODE REVIEW

**Comment by aandrewww** [comment]
Thanks for the PR
I don't have free time right now, but I'll review it in a few weeks.

**Comment by malikdoksoz** [comment]
updated to @sentry/node@**7.2.0**

**Comment by segevfiner** [comment]
I wasn't sure what's the status of it since it was marked as draft. If yours is better than it should be preferred and this one closed.

**Comment by glensc** [comment]
it's written in the comments why it's in the draft.

**Comment by segevfiner** [comment]
Yeah, I noticed now.

**Comment by segevfiner** [comment]
@glensc It does. 👍

**Pull request closed without merging**
